### ISSUE TITLE
Double slashes in canonical URL

### ISSUE THREAD

**Issue by architchandra** [idkshite/idkshite.com#2]
Hi

I am trying to translate swyx's _Learn in Public_ article into Hindi, as you've done with German.

On [your webpage](https://idkshite.com/posts/learn-in-public), I noticed that you've accidentally put two slashes in the canonical URL (and a few other meta tags as well). Hope this helps you identify the issue. :)

Sorry to use this Github issue as a message, but I was wondering if I should add `hreflang` or `canonical` tags pointing to the original article from swyx to indicate that my article is a translation and not a duplicate. Do you have any opinion on that, SEO-wise? Have you seen Google complain about duplicate content for your translation?

Thanks a lot! 🙂

**Comment by idkshite** [comment]
Hi @architchandra,
thanks for spotting this bug and telling me about it 🙌

About the `hreflang` and `canonical`. They way I understand it. `hreflang` is mainly used to differentiate between translations on **one domain**. In this case the posts are spread among many domains, so i'm not sure if it's the right tool here. Therefore I would reach for the `canonical` (if any). Personally I don't see this as duplicate content. So I refrained from adjusting the canonical tag to the original post url. So far I didn't perceive any disadvantages in the Google ranking of the article. 🙂

**Comment by architchandra** [comment]
I was tilting in the same direction and your comment has reinforced my decision. 
Thanks @idkshite.
